name: image_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - python=3.7
  - numpy
  - pip
  - matplotlib
  - pandas
  - ipython
  - jupyterlab
  - pip:
    - natsort
    - sklearn
    - scipy
